language: node_js
sudo: false
notifications:
  email:
    recipients:
      - tristan.wright@kitware.com
      - sebastien.jourdain@kitware.com
    on_success: change
    on_failure: always
cache:
  directories:
    - node_modules
    - documentation/www/node_modules
node_js:
  - "5.1"
env:
  - CXX=g++-4.8
addons:
  sources:
    - ubuntu-toolchain-r-test
  apt:
    packages:
      - g++-4.8
      - xvfb
env:
  CXX=g++-4.8

before_script:
  - export DISPLAY=:99.0; sh -e /etc/init.d/xvfb start
  - sleep 3

script:
  - npm run build:release -- --bail
  - npm run test:travis
  - git config --global user.name "Travis CI"
  - git config --global user.email "sebastien.jourdain@kitware.com"
  - export GIT_PUBLISH_URL=https://${GH_TOKEN}@github.com/Kitware/paraviewweb.git
  - if [ "$TRAVIS_BRANCH" == "master" ]; then npm run doc:publish; fi
after_success:
  - npm run semantic-release
branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
