title: ParaViewWeb
description: "ParaViewWeb is a Web framework which allow to bring the power of ParaView and VTK into the Web."
subtitle: "Small framework for bringing scientific visualization to the Web"
author: Kitware Inc.
language: en
timezone: UTC
url: https://kitware.github.io/paraviewweb
root: /paraviewweb/
permalink: news/:year/:month/:day/:title/
archive_dir: news
code_dir: downloads/code
new_post_name: :year-:month-:day-:title.md # File name of new posts
post_asset_folder: true
highlight:
  enable: true
  line_number: false
per_page: 0

theme: navy

google_analytics:
github: kitware/paraviewweb
